### ISSUE TITLE
Scuttlebutt: Rede social P2P baseada na blockchain

### ISSUE THREAD

**Issue by klarkc** [ancap-devs/forum#1]
Olá pessoal, gostaria de divulgar a plataforma de rede social [scuttlebutt.nz](https://www.scuttlebutt.nz/) e nosso [Pub Ancap](http://publibertynetwork.tk), que hoje já tem 250 seguidores.

![patchwork](https://d33wubrfki0l68.cloudfront.net/338169b7ef19bc572a20c04a259f9a90097fa1bd/da714/assets/screenshots/patchwork.jpg)

O scuttlebutt é um conceito de rede de rumores, onde os dados públicos são trocados entre os usuários que se seguem, não estando centralizado em uma entidade. Os pubs são apenas "locais" fictícios onde os usuários podem interagir e compartilhar conteúdo entre si.

**Comment by AnCaPepe** [comment]
Faz uso de GNU Social como o Mastodon?

**Comment by AnCaPepe** [comment]
Pessoal do Minds.com está com um projeto de rede p2p também
https://gitlab.com/minds/nomad

**Comment by klarkc** [comment]
> Mastodon

Não, é uma plataforma independente do Mastodon. Diferentemente do Mastodon que é uma "federação" de servidores que compartilham os dados, o Scuttlebutt é totalmente p2p - todos os clientes tem todos os dados e compartilham com os pubs, que exercem a função de ponto de sincronização entre os peers. Apenas os peers que se seguem tem as chaves e podem ler os dados criptografados (parecido com a blockchain).
